name: 'Trigger Helm Deployment'
description: 'Trigger production deployment for Helm charts'

inputs:
  app_version:
    required: false
    type: string
  charts:
    required: true
    type: string
  repo:
    required: true
    type: string
  token:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Extract version information
    id: version
    shell: bash
    run: |
      if [ "${{ github.event_name }}" = "release" ]; then
        # Extract version from release tag
        VERSION="${{ github.event.release.tag_name }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        echo "app_version=$VERSION" >> $GITHUB_OUTPUT
        echo "trigger_source=release" >> $GITHUB_OUTPUT
        echo "release_name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
      elif [ "${{ github.event_name }}" = "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
        # Extract version from tag
        VERSION="${{ github.ref_name }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        echo "app_version=$VERSION" >> $GITHUB_OUTPUT
        echo "trigger_source=tag" >> $GITHUB_OUTPUT
      else
        # Manual workflow dispatch
        echo "app_version=${{ github.event.inputs.app_version }}" >> $GITHUB_OUTPUT
        echo "trigger_source=manual" >> $GITHUB_OUTPUT
      fi

  - name: Set deployment parameters
    id: params
    shell: bash
    run: |
      APP_VERSION="${{ steps.version.outputs.app_version }}"
      CHARTS="${{ github.event.inputs.charts }}"
      TARGET_REPO="${{ github.event.inputs.repo }}"

      echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
      echo "charts=$CHARTS" >> $GITHUB_OUTPUT
      echo "target_repo=$TARGET_REPO" >> $GITHUB_OUTPUT

      echo "Will trigger deployment with:"
      echo "  - App Version: $APP_VERSION"
      echo "  - Charts: ${CHARTS:-'all'}"
      echo "  - Target Repo: $TARGET_REPO"
      echo "  - Trigger Source: ${{ steps.version.outputs.trigger_source }}"

  - name: Trigger production deployment
    uses: peter-evans/repository-dispatch@v3
    with:
      token: ${{ inputs.deployment_token }}
      repository: ${{ steps.params.outputs.target_repo }}
      event-type: deploy-production
      client-payload: |
        {
          "app_version": "${{ steps.params.outputs.app_version }}",
          "charts": "${{ steps.params.outputs.charts }}",
          "source_repo": "${{ github.repository }}",
          "source_ref": "${{ github.ref }}",
          "source_sha": "${{ github.sha }}",
          "trigger_source": "${{ steps.version.outputs.trigger_source }}",
          "triggered_by": "${{ github.actor }}"
        }

  - name: Create deployment summary
    shell: bash
    run: |
      echo "## Production Deployment Triggered" >> $GITHUB_STEP_SUMMARY
      echo "- **App Version**: ${{ steps.params.outputs.app_version }}" >> $GITHUB_STEP_SUMMARY
      echo "- **Charts**: ${{ steps.params.outputs.charts || 'all' }}" >> $GITHUB_STEP_SUMMARY
      echo "- **Target Repository**: ${{ steps.params.outputs.target_repo }}" >> $GITHUB_STEP_SUMMARY
      echo "- **Trigger Source**: ${{ steps.version.outputs.trigger_source }}" >> $GITHUB_STEP_SUMMARY
      echo "- **Triggered By**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
      echo "" >> $GITHUB_STEP_SUMMARY
      echo "The deployment workflow has been triggered in the cloud configuration repository." >> $GITHUB_STEP_SUMMARY
      echo "Monitor the deployment progress at: https://github.com/${{ steps.params.outputs.target_repo }}/actions" >> $GITHUB_STEP_SUMMARY

  - name: Notify deployment trigger failure
    if: failure()
    shell: bash
    run: |
      echo "❌ Failed to trigger production deployment"
      echo "Repository: ${{ github.repository }}"
      echo "Event: ${{ github.event_name }}"
      echo "Actor: ${{ github.actor }}"
      echo "Ref: ${{ github.ref }}"

      # You can add additional notification logic here
      # such as sending to Slack, Discord, email, etc.
